"""UN WPP location name -> ISO alpha-3 code mapping for choropleth maps."""

COUNTRY_TO_ISO3 = {
    'Afghanistan': 'AFG', 'Albania': 'ALB', 'Algeria': 'DZA', 'American Samoa': 'ASM',
    'Andorra': 'AND', 'Angola': 'AGO', 'Anguilla': 'AIA', 'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG', 'Armenia': 'ARM', 'Aruba': 'ABW', 'Australia': 'AUS',
    'Austria': 'AUT', 'Azerbaijan': 'AZE', 'Bahamas': 'BHS', 'Bahrain': 'BHR',
    'Bangladesh': 'BGD', 'Barbados': 'BRB', 'Belarus': 'BLR', 'Belgium': 'BEL',
    'Belize': 'BLZ', 'Benin': 'BEN', 'Bermuda': 'BMU', 'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL', 'Bonaire, Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH', 'Botswana': 'BWA', 'Brazil': 'BRA',
    'British Virgin Islands': 'VGB', 'Brunei Darussalam': 'BRN', 'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA', 'Burundi': 'BDI', 'Cabo Verde': 'CPV', 'Cambodia': 'KHM',
    'Cameroon': 'CMR', 'Canada': 'CAN', 'Cayman Islands': 'CYM',
    'Central African Republic': 'CAF', 'Chad': 'TCD', 'Chile': 'CHL', 'China': 'CHN',
    'China, Hong Kong SAR': 'HKG', 'China, Macao SAR': 'MAC',
    'China, Taiwan Province of China': 'TWN', 'Colombia': 'COL', 'Comoros': 'COM',
    'Congo': 'COG', 'Cook Islands': 'COK', 'Costa Rica': 'CRI', 'Croatia': 'HRV',
    'Cuba': 'CUB', 'Cura\u00e7ao': 'CUW', 'Cyprus': 'CYP', 'Czechia': 'CZE',
    "C\u00f4te d'Ivoire": 'CIV', "Dem. People's Republic of Korea": 'PRK',
    'Democratic Republic of the Congo': 'COD', 'Denmark': 'DNK', 'Djibouti': 'DJI',
    'Dominica': 'DMA', 'Dominican Republic': 'DOM', 'Ecuador': 'ECU', 'Egypt': 'EGY',
    'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ', 'Eritrea': 'ERI', 'Estonia': 'EST',
    'Eswatini': 'SWZ', 'Ethiopia': 'ETH', 'Falkland Islands (Malvinas)': 'FLK',
    'Faroe Islands': 'FRO', 'Fiji': 'FJI', 'Finland': 'FIN', 'France': 'FRA',
    'French Guiana': 'GUF', 'French Polynesia': 'PYF', 'Gabon': 'GAB', 'Gambia': 'GMB',
    'Georgia': 'GEO', 'Germany': 'DEU', 'Ghana': 'GHA', 'Gibraltar': 'GIB',
    'Greece': 'GRC', 'Greenland': 'GRL', 'Grenada': 'GRD', 'Guadeloupe': 'GLP',
    'Guam': 'GUM', 'Guatemala': 'GTM', 'Guinea': 'GIN', 'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY', 'Haiti': 'HTI', 'Holy See': 'VAT', 'Honduras': 'HND',
    'Hungary': 'HUN', 'Iceland': 'ISL', 'India': 'IND', 'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN', 'Iraq': 'IRQ', 'Ireland': 'IRL',
    'Isle of Man': 'IMN', 'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM',
    'Japan': 'JPN', 'Jordan': 'JOR', 'Kazakhstan': 'KAZ', 'Kenya': 'KEN',
    'Kiribati': 'KIR', 'Kuwait': 'KWT', 'Kyrgyzstan': 'KGZ',
    "Lao People's Democratic Republic": 'LAO', 'Latvia': 'LVA', 'Lebanon': 'LBN',
    'Lesotho': 'LSO', 'Liberia': 'LBR', 'Libya': 'LBY', 'Liechtenstein': 'LIE',
    'Lithuania': 'LTU', 'Luxembourg': 'LUX', 'Madagascar': 'MDG', 'Malawi': 'MWI',
    'Malaysia': 'MYS', 'Maldives': 'MDV', 'Mali': 'MLI', 'Malta': 'MLT',
    'Marshall Islands': 'MHL', 'Martinique': 'MTQ', 'Mauritania': 'MRT',
    'Mauritius': 'MUS', 'Mayotte': 'MYT', 'Mexico': 'MEX',
    'Micronesia (Fed. States of)': 'FSM', 'Monaco': 'MCO', 'Mongolia': 'MNG',
    'Montenegro': 'MNE', 'Montserrat': 'MSR', 'Morocco': 'MAR', 'Mozambique': 'MOZ',
    'Myanmar': 'MMR', 'Namibia': 'NAM', 'Nauru': 'NRU', 'Nepal': 'NPL',
    'Netherlands': 'NLD', 'New Caledonia': 'NCL', 'New Zealand': 'NZL',
    'Nicaragua': 'NIC', 'Niger': 'NER', 'Nigeria': 'NGA', 'Niue': 'NIU',
    'North Macedonia': 'MKD', 'Northern Mariana Islands': 'MNP', 'Norway': 'NOR',
    'Oman': 'OMN', 'Pakistan': 'PAK', 'Palau': 'PLW', 'Panama': 'PAN',
    'Papua New Guinea': 'PNG', 'Paraguay': 'PRY', 'Peru': 'PER', 'Philippines': 'PHL',
    'Poland': 'POL', 'Portugal': 'PRT', 'Puerto Rico': 'PRI', 'Qatar': 'QAT',
    'Republic of Korea': 'KOR', 'Republic of Moldova': 'MDA', 'Romania': 'ROU',
    'Russian Federation': 'RUS', 'Rwanda': 'RWA', 'R\u00e9union': 'REU',
    'Saint Barth\u00e9lemy': 'BLM', 'Saint Helena': 'SHN', 'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA', 'Saint Martin (French part)': 'MAF',
    'Saint Pierre and Miquelon': 'SPM', 'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM', 'San Marino': 'SMR', 'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU', 'Senegal': 'SEN', 'Serbia': 'SRB', 'Seychelles': 'SYC',
    'Sierra Leone': 'SLE', 'Singapore': 'SGP', 'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK', 'Slovenia': 'SVN', 'Solomon Islands': 'SLB', 'Somalia': 'SOM',
    'South Africa': 'ZAF', 'South Sudan': 'SSD', 'Spain': 'ESP', 'Sri Lanka': 'LKA',
    'State of Palestine': 'PSE', 'Sudan': 'SDN', 'Suriname': 'SUR', 'Sweden': 'SWE',
    'Switzerland': 'CHE', 'Syrian Arab Republic': 'SYR', 'Tajikistan': 'TJK',
    'Thailand': 'THA', 'Timor-Leste': 'TLS', 'Togo': 'TGO', 'Tokelau': 'TKL',
    'Tonga': 'TON', 'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN',
    'Turkmenistan': 'TKM', 'Turks and Caicos Islands': 'TCA', 'Tuvalu': 'TUV',
    'T\u00fcrkiye': 'TUR', 'Uganda': 'UGA', 'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE', 'United Kingdom': 'GBR',
    'United Republic of Tanzania': 'TZA', 'United States Virgin Islands': 'VIR',
    'United States of America': 'USA', 'Uruguay': 'URY', 'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT', 'Venezuela (Bolivarian Republic of)': 'VEN', 'Viet Nam': 'VNM',
    'Wallis and Futuna Islands': 'WLF', 'Western Sahara': 'ESH', 'Yemen': 'YEM',
    'Zambia': 'ZMB', 'Zimbabwe': 'ZWE',
}
